# Project
version=3.0.0
group=com.nine.ironladders
java_version=17

# Unified-Publishing
fabric_release_type = release
forge_release_type = release
modrinth_project_id=tWPvfGAB
curseforge_project_id=974844

# Common
minecraft_version=1.20.1
mod_name=Iron Ladders
mod_author=Nine
mod_id=ironladders
license=LGPL v3.0
credits=
description=Ladders with increased climb speed.
minecraft_version_range=[1.20.1, 1.22)

parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.4.1
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# REI JEI EMI
fabric_nei=EMI
forge_nei=EMI

# JADE WTHIT
fabric_waila=JADE

# JADE TOP WTHIT
forge_waila=WTHIT

jade_fabric_version=11.13.1+fabric
jade_forge_version=11.13.2+forge

top_version=1.20.1-10.0.3

wthit_fabric_version=fabric-8.21.0
wthit_forge_version=forge-8.21.0
badpackets_fabric_version=fabric-0.4.3
badpackets_forge_version=forge-0.4.3


jei_version=15.20.0.112
rei_version=12.1.785
emi_version=1.1.22

mekanism_version=1.20.1-10.4.6.20

techreborn_curse_project_id=233564
techreborn_fabric_curse_file_id=4708962

reborncore_curse_project_id=237903
reborncore_fabric_curse_file_id=4708961

teamreborn_energy_version=3.0.0

modmenu_version=7.2.2
