# Project
version=3.0.02
group=com.nine.ironladders
java_version=21

# Unified-Publishing
fabric_release_type = release
forge_release_type = release
neoforge_release_type = release
modrinth_project_id=tWPvfGAB
curseforge_project_id=974844

# Common
minecraft_version=1.21.1
mod_name=Iron Ladders
mod_author=Nine
mod_id=ironladders
license=LGPL v3.0
credits=
description=Ladders with increased climb speed.
minecraft_version_range=[1.21.1, 1.22)

neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.8+1.21.1
fabric_loader_version=0.16.10

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.234
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:/Program Files/Java/jdk-21

# REI JEI EMI
fabric_nei=EMI
neoforge_nei=JEI
#JEI
forge_nei=JEI

# JADE WTHIT
fabric_waila=JADE

# JADE TOP WTHIT
forge_waila=WTHIT
neoforge_waila=WTHIT

jade_fabric_version=15.10.5+fabric
jade_forge_version=15.10.5+forge
jade_neoforge_version=15.10.5+neoforge
jade_common_version=15.10.5+neoforge

top_version=1.21_neo-12.0.8
top_neoforge_version=1.21_neo-12.0.8

wthit_fabric_version=fabric-12.10.1
wthit_forge_version=forge-12.10.1
wthit_neoforge_version=neo-12.10.1
wthit_common_version=neo-12.10.1
badpackets_fabric_version=fabric-0.8.2
badpackets_forge_version=forge-0.8.2
badpackets_neoforge_version=neo-0.8.2
badpackets_common_version=neo-0.8.2


jei_version=19.27.0.340
rei_version=16.0.799
emi_version=1.1.22

mekanism_version=10.7.17.83
architectury_forge_version=10.1.20
architectury_neoforge_version=13.0.8
cloth_config_forge_version=15.0.140
cloth_config_neoforge_version=15.0.140

techreborn_curse_project_id=233564
techreborn_fabric_curse_file_id=4708962

reborncore_curse_project_id=237903
reborncore_fabric_curse_file_id=4708961

teamreborn_energy_version=4.1.0

modmenu_version=11.0.3
