plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
    id "me.shedaniel.unified-publishing"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = true

    reobf = false

    runs {
        client {
            workingDirectory file('runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory file('runs/data')
            ideaModule "${rootProject.name}.${project.name}.main"

            def generated = file('src/generated/resources').absolutePath
            def existing = file('src/main/resources').absolutePath

            args(
                    '--mod', mod_id,
                    '--all',
                    '--output', generated,
                    '--existing', existing
            )
            taskName 'Data'
            mods {
                modDataRun {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
            srcDir project(':common').file('src/generated/resources')
            srcDir project(':common').file('src/main/resources')
        }
    }
}
sourceSets.main.resources.srcDir 'src/generated/resources'

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    // Forge's hack fix
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    // NEI APIs
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}"

    // NEI runtime
    def nei = (findProperty("forge_nei") ?: "JEI").toString().toUpperCase(Locale.ROOT)
    def neiRuntime = [
            JEI: {
                add("implementation", "mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
            }
    ]
    neiRuntime[nei]?.call()
}





base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

jar {
    archiveFileName.set("${mod_id}-forge-${minecraft_version}-${project.version}.jar")
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

configureUnifiedPublishing(project, [
        loaderName: "Forge",
        gameLoader: "forge",
        releaseType: rootProject.forge_release_type,
        publicationTask: "jar"
])

